/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

result *
suma_1(double n1, double n2,  CLIENT *clnt)
{
	suma_1_argument arg;
	static result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, suma, (xdrproc_t) xdr_suma_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

result *
multiplica_1(double n1, double n2,  CLIENT *clnt)
{
	multiplica_1_argument arg;
	static result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, multiplica, (xdrproc_t) xdr_multiplica_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

result *
divide_1(double n1, double n2,  CLIENT *clnt)
{
	divide_1_argument arg;
	static result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, divide, (xdrproc_t) xdr_divide_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

result *
resta_1(double n1, double n2,  CLIENT *clnt)
{
	resta_1_argument arg;
	static result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, resta, (xdrproc_t) xdr_resta_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vect *
suma_vectores_1(vect n1, vect n2,  CLIENT *clnt)
{
	suma_vectores_1_argument arg;
	static vect clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.n1 = n1;
	arg.n2 = n2;
	if (clnt_call (clnt, suma_vectores, (xdrproc_t) xdr_suma_vectores_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_vect, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
