/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

#define suma_tipo 0
#define multiplica_tipo 1
#define divide_tipo 2
#define resta_tipo 3

double
calculadora_1(char *host, double n1, double n2, int tipo)
{
	CLIENT *clnt;
	result  *result_1;
	// double suma_1_n1;
	// double suma_1_n2;
	// result  *result_2;
	// double multiplica_1_n1;
	// double multiplica_1_n2;
	// result  *result_3;
	// double divide_1_n1;
	// double divide_1_n2;
	// result  *result_4;
	// double resta_1_n1;
	// double resta_1_n2;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if(tipo == suma_tipo){
		result_1 = suma_1(n1, n2, clnt);
		if (result_1 == (result *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
	else if(tipo == multiplica_tipo){
		result_1 = multiplica_1(n1, n2, clnt);
		if (result_1 == (result *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
	else if(tipo == divide_tipo){
		result_1 = divide_1(n1, n2, clnt);
		if (result_1 == (result *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
	else if(tipo == resta_tipo){
		result_1 = resta_1(n1, n2, clnt);
		if (result_1 == (result *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	int error = result_1->code;

	if (error > 0){
		printf("Operación no válida: código de error %d\n", error);

		if (error == 1){
			printf("División por cero\n");
		}

		exit (1);
	}

	return result_1->valor_resultado;
}

double
calculadora_2(char *host, double* n1, double* n2, int tipo)
{
	CLIENT *clnt;
	result  *result_1;
	// double suma_1_n1;
	// double suma_1_n2;
	// result  *result_2;
	// double multiplica_1_n1;
	// double multiplica_1_n2;
	// result  *result_3;
	// double divide_1_n1;
	// double divide_1_n2;
	// result  *result_4;
	// double resta_1_n1;
	// double resta_1_n2;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if(tipo == suma_tipo){
		result_1 = suma_1(n1, n2, clnt);
		if (result_1 == (result *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
	else if(tipo == multiplica_tipo){
		result_1 = multiplica_1(n1, n2, clnt);
		if (result_1 == (result *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
	else if(tipo == divide_tipo){
		result_1 = divide_1(n1, n2, clnt);
		if (result_1 == (result *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}
	else if(tipo == resta_tipo){
		result_1 = resta_1(n1, n2, clnt);
		if (result_1 == (result *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	int error = result_1->code;

	if (error > 0){
		printf("Operación no válida: código de error %d\n", error);

		if (error == 1){
			printf("División por cero\n");
		}

		exit (1);
	}

	return result_1->valor_resultado;
}


int
main (int argc, char *argv[])
{
	char *host;
	char operador;
	double n1 = 0.0, n2 = 0.0;
	double resultado = 0.0;

	if (argc < 2) {
		printf ("usage: %s <maquina>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	// operador = argv[3][0];
	// n1 = atof(argv[2]);
	// n2 = atof(argv[4]);

	int tipo;
	int opcion;

	int salir = 0;

	while( salir == 0){
		printf("Menu:\n");
		printf("1. Sumar\n");
		printf("2. Restar\n");
		printf("3. Multiplicar\n");
		printf("4. Dividir\n");
		printf("5. Salir\n");

		scanf("%d", &opcion);

		switch (opcion)
		{
			case 1:
				tipo = suma_tipo;
				operador = '+';
				break;
			case 2:
				tipo = resta_tipo;
				operador = '-';
				break;
			case 3:
				tipo = multiplica_tipo;
				operador = '*';
				break;
			case 4:
				tipo = divide_tipo;
				operador = '/';
				break;
			case 5:
				salir = 1;
				break;
			default:
				printf("Operador no valido\n"); // y se sigue preguntando que quiere?
				break;
		}

		if(salir == 0){
			printf("\nInserte operandos: ");
			scanf("%lf %lf", &n1, &n2);

			resultado = calculadora_1 (host, n1, n2, tipo);

			printf("\nEl resultado de %f %c %f es %f\n\n",
				n1, operador, n2, resultado);
		}

	} // bucle mientras salir es false

	exit (0);
}
