/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dir.h"

bool_t
xdr_nums (XDR *xdrs, nums *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct numeros), (xdrproc_t) xdr_numeros))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_num (XDR *xdrs, num *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_numeros (XDR *xdrs, numeros *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num_1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readdir_res (XDR *xdrs, readdir_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_num (xdrs, &objp->readdir_res_u.result))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
