/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

result *
suma_1_svc(double n1, double n2,  struct svc_req *rqstp)
{
	static result  result;

	result.valor_resultado = n1+n2;
	result.code = 0;

	return &result;
}

result *
multiplica_1_svc(double n1, double n2,  struct svc_req *rqstp)
{
	static result  result;

	result.valor_resultado = n1*n2;
	result.code = 0;

	return &result;
}

result *
divide_1_svc(double n1, double n2,  struct svc_req *rqstp)
{
	static result  result;

	if(n2 == 0){
		result.code = 1;
		printf("División por cero\n\n");
	}
	else{
		result.valor_resultado = n1/n2;
		result.code = 0;
	}

	return &result;
}

result *
resta_1_svc(double n1, double n2,  struct svc_req *rqstp)
{
	static result  result;

	result.valor_resultado = n1-n2;
	result.code = 0;

	return &result;
}

vect *
suma_vectores_1_svc(vect n1, vect n2,  struct svc_req *rqstp)
{
	static vect  result;

	result.vect_len = 5;
	result.vect_val = (double *)malloc(result.vect_len * sizeof(double));


	for(int i=0; i<5; i++){
		result.vect_val[i] = n1.vect_val[i] + n2.vect_val[i];
	}

	return &result;
}
